-- UI plugins
return {
  require('plugins.ui.tokyonight'),
  require('plugins.ui.onedark'),
  require('plugins.ui.notify'),
  require('plugins.ui.lualine'),
  require('plugins.ui.mini-modules'),
  require('plugins.ui.tabby'),
  require('plugins.ui.aerial'),
  require('plugins.ui.noice'),
  require('plugins.ui.trouble'),
  require('plugins.ui.output-panel'),
  require('plugins.ui.todo-comments'),
  require('plugins.ui.scrollbar'),
  require('plugins.ui.numb'),
  require('plugins.ui.cursorline'),
  require('plugins.ui.beacon'),
  require('plugins.ui.modes'),
  require('plugins.ui.indent-blankline'),
  require('plugins.ui.matchparen'),
  require('plugins.ui.nvim-navic'),
  require('plugins.ui.sidebar'),
  require('plugins.ui.cinnamon'),
}
