# Helix Editor Configuration

theme = "tokyonight"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"
cursorline = true
auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
ignore = true
deduplicate-links = true

[editor.lsp]
display-messages = true
auto-signature-help = true

[editor.indent-guides]
render = true

[keys.normal]
"backspace" = { w = ":w", q = ":bc", c = ":sh gradle run --quiet", l = ":sh lsd", t =":sh cargo nextest run", r = ":reload"}
