-- Emmet LSP server configuration
return {
	settings = {
		emmet = {
			includeLanguages = {
				typescript = "html",
				typescriptreact = "html",
				javascript = "html",
				javascriptreact = "html",
				vue = "html",
				svelte = "html",
				astro = "html",
				["astro-markdown"] = "html",
				["html-eex"] = "html",
				["phoenix-heex"] = "html",
				heex = "html",
				eelixir = "html",
				erb = "html",
			},
			showExpandedAbbreviation = "always",
			showAbbreviationSuggestions = true,
			showSuggestionsAsSnippets = true,
			preferences = {
				["css.propertyEnd"] = ";",
				["css.valueSeparator"] = ": ",
				["html.format.enable"] = true,
				["html.format.wrapLineLength"] = 120,
				["html.format.indentInnerHtml"] = true,
				["html.format.preserveNewLines"] = true,
				["html.format.maxPreserveNewLines"] = 2,
				["html.format.indentHandlebars"] = false,
				["html.format.endWithNewline"] = false,
				["html.format.extraLiners"] = "head, body, /html",
				["html.format.wrapAttributes"] = "auto",
			},
			variables = {
				lang = "en",
				locale = "en-US",
				charset = "UTF-8",
			},
		},
	},
	filetypes = {
		"astro",
		"css",
		"eruby",
		"html",
		"htmldjango",
		"javascriptreact",
		"less",
		"pug",
		"sass",
		"scss",
		"svelte",
		"typescriptreact",
		"vue",
		"xml",
	},
	init_options = {
		html = {
			options = {
				["bem.enabled"] = true,
				["bem.element"] = "__",
				["bem.modifier"] = "--",
				["jsx.enabled"] = true,
				["markup.attributes"] = {
					class = "className",
					["for"] = "htmlFor",
				},
			},
		},
	},
	single_file_support = true,
}
