-- Tailwind CSS LSP server configuration
return {
  settings = {
    tailwindCSS = {
      lint = {
        cssConflict = 'warning',
        invalidApply = 'error',
        invalidConfigPath = 'error',
        invalidScreen = 'error',
        invalidTailwindDirective = 'error',
        invalidVariant = 'error',
        recommendedVariantOrder = 'warning',
      },
      validate = true,
      classAttributes = { 'class', 'className', 'class:list', 'classList', 'ngClass' },
      includeLanguages = {
        typescript = 'javascript',
        typescriptreact = 'javascript',
        ['html-eex'] = 'html',
        ['phoenix-heex'] = 'html',
        heex = 'html',
        eelixir = 'html',
        elm = 'html',
        erb = 'html',
        svelte = 'html',
        vue = 'html',
        astro = 'html',
        rust = 'html',
      },
      experimental = {
        classRegex = {
          'tw`([^`]*)',
          'tw="([^"]*)',
          'tw={"([^"}]*)',
          'tw\\.\\w+`([^`]*)',
          'tw\\(.*?\\)`([^`]*)',
          { 'clsx\\(([^)]*)\\)', '(?:\'|"|`)([^\']*)(?:\'|"|`)' },
          { 'classnames\\(([^)]*)\\)', '\'([^\']*)\'' },
          { 'cva\\(([^)]*)\\)', '["\'`]([^"\'`]*).*?["\'`]' },
          { 'cx\\(([^)]*)\\)', '(?:\'|"|`)([^\']*)(?:\'|"|`)' },
        },
      },
      emmetCompletions = false,
      colorDecorators = true,
      suggestions = true,
      hovers = true,
      codeActions = true,
    },
  },
  filetypes = {
    'astro',
    'astro-markdown',
    'html',
    'css',
    'less',
    'postcss',
    'sass',
    'scss',
    'stylus',
    'javascript',
    'javascriptreact',
    'typescript',
    'typescriptreact',
    'vue',
    'svelte',
    'templ',
  },
  init_options = {
    userLanguages = {
      templ = 'html',
    },
  },
  root_dir = function(fname)
    return require('lspconfig.util').root_pattern(
      'tailwind.config.js',
      'tailwind.config.cjs',
      'tailwind.config.mjs',
      'tailwind.config.ts',
      'postcss.config.js',
      'postcss.config.cjs',
      'postcss.config.mjs',
      'postcss.config.ts',
      'package.json',
      'node_modules',
      '.git'
    )(fname)
  end,
  settings_file_pattern = 'tailwind%.config%.[jt]s',
}
