[mgr]
ratio = [1, 3, 4]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "size"
show_hidden = false
show_symlink = true
scrolloff = 5
mouse_events = ["click", "scroll"]
title_format = "yazi: {cwd}"

[manager]
cache_dir = "~/.cache/yazi"

[preview]
wrap = "no"
tab_size = 2
max_width = 600
max_height = 600
image_delay = 20
image_filter = "lanczos3"
image_quality = 70

[tasks]
micro_workers = 10
macro_workers = 5
bizarre_retry = 3
suppress_preload = false

[opener]
edit = [
  { run = 'swaymsg [app_id=yazi-explorer] move scratchpad; ~/.config/yazi/scripts/edit-in-kitty.sh "$@"', desc = "nvim in kitty" },
]
open_terminal = [
  { run = 'swaymsg [app_id=yazi-explorer] move scratchpad; ~/.config/yazi/scripts/open-terminal.sh "$1"', desc = "Terminal here" },
]
open = [
  { run = 'swaymsg [app_id=yazi-explorer] move scratchpad; xdg-open "$@"', desc = "xdg-open" },
]
reveal = [
  { run = 'xdg-open "$(dirname "$1")"', desc = "Reveal in file manager" },
]

[open]
rules = [
  { mime = "text/*", use = "edit" },
  { mime = "application/json", use = "edit" },
  { mime = "application/xml", use = "edit" },
  { mime = "inode/directory", use = "open_terminal" },
  { mime = "image/*", use = "open" },
  { mime = "video/*", use = "open" },
  { mime = "audio/*", use = "open" },
  { mime = "application/pdf", use = "open" },
  { mime = "inode/x-empty", use = "edit" },
  { mime = "*", use = "open" },
]
